name: project_env
channels:
  - pytorch
  - nvidia
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _sysroot_linux-64_curr_repodata_hack=3
  - aom=3.5.0
  - archspec=0.2.3
  - aria2=1.37.0
  - atomicwrites=1.4.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bwa=0.7.19
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.6.15
  - cffi=1.17.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.9
  - curl=8.14.1
  - expat=2.7.1
  - ffmpeg=5.1.2
  - foldseek=10.941cd33
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.13.3
  - gawk=5.3.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - intel-openmp=2021.4.0
  - jpeg=9e
  - k8=1.2
  - kernel-headers_linux-64=3.10.0
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libasprintf=0.24.1
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcurl=8.14.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgettextpo=0.24.1
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - libiconv=1.18
  - libidn2=2.3.4
  - libnghttp2=1.64.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libopenblas=0.3.29
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.50
  - libsqlite=3.45.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.18.0
  - libvpx=1.11.0
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - macrel=1.5.0
  - megahit=1.2.9
  - minimap2=2.30
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - ncurses=6.4
  - nettle=3.9.1
  - networkx=3.2.1
  - ngless=1.5.0
  - numexpr=2.8.4
  - openh264=2.3.1
  - openjpeg=2.5.2
  - openssl=3.5.0
  - p11-kit=0.24.1
  - packaging=24.2
  - paladin=1.4.6
  - perl=5.40.2
  - pip=25.1
  - prodigal=2.6.3
  - pthread-stubs=0.3
  - pycparser=2.21
  - pyrodigal=3.6.3.post1
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.32.4
  - samtools=1.3.1
  - scikit-learn=1.2.0
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.45.2
  - svt-av1=1.4.1
  - sysroot_linux-64=2.17
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - typing_extensions=4.12.2
  - tzdata=2025b
  - tzlocal=5.2
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-xextproto=7.3.0
  - xorg-xorgproto=2024.1
  - xorg-xproto=7.0.31
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==1.8.1
      - adagio==0.2.6
      - ag2==0.9.3
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiohttp-cors==0.8.1
      - aiosignal==1.4.0
      - alembic==1.16.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - appdirs==1.4.4
      - argparse==1.4.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - asyncer==0.0.8
      - attrs==25.3.0
      - autogluon==1.4.0
      - autogluon-common==1.4.0
      - autogluon-core==1.4.0
      - autogluon-features==1.4.0
      - autogluon-multimodal==1.4.0
      - autogluon-tabular==1.4.0
      - autogluon-timeseries==1.4.0
      - beautifulsoup4==4.13.4
      - biopython==1.85
      - bitsandbytes==0.46.1
      - blessed==1.21.0
      - blis==1.2.1
      - boto3==1.40.1
      - botocore==1.40.1
      - cachetools==5.5.2
      - catalogue==2.0.10
      - catboost==1.2.8
      - certifi==2025.8.3
      - chardet==5.2.0
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cloudpathlib==0.21.1
      - cloudpickle==3.1.1
      - cmake==3.25.0
      - colorama==0.4.6
      - colorful==0.5.7
      - colorlog==6.9.0
      - confection==0.1.5
      - contourpy==1.2.1
      - coreforecast==0.0.16
      - cycler==0.12.1
      - cymem==2.0.11
      - datasets==4.0.0
      - defusedxml==0.7.1
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - docker==7.1.0
      - einx==0.3.0
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - evaluate==0.4.5
      - exceptiongroup==1.3.0
      - fastai==2.7.19
      - fastcore==1.7.29
      - fastdownload==0.0.7
      - fastprogress==1.0.3
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fonttools==4.58.5
      - frozendict==2.4.6
      - frozenlist==1.7.0
      - fs==2.4.16
      - fsspec==2025.3.0
      - fugue==0.9.1
      - future==1.0.0
      - gast==0.4.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gluonts==0.16.2
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1
      - google-api-python-client==2.178.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==0.4.6
      - google-genai==1.29.0
      - google-generativeai==0.8.5
      - google-pasta==0.2.0
      - googleapis-common-protos==1.70.0
      - gpustat==1.1.1
      - greenlet==3.2.3
      - grpcio==1.73.1
      - grpcio-status==1.71.2
      - gym==0.23.1
      - gym-notices==0.0.8
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.33.0
      - hydra-core==1.3.2
      - hyperopt==0.2.7
      - idna==3.10
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - jiter==0.10.0
      - jmespath==1.0.1
      - joblib==1.5.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - keras==2.11.0
      - kiwisolver==1.4.7
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - libclang==18.1.1
      - lightgbm==4.6.0
      - lightning==2.5.2
      - lightning-utilities==0.15.0
      - lit==15.0.7
      - llvmlite==0.43.0
      - loguru==0.7.3
      - mako==1.3.10
      - marisa-trie==1.2.1
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mlforecast==0.14.0
      - model-index==0.1.11
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.3
      - multiprocess==0.70.16
      - murmurhash==1.0.13
      - narwhals==2.0.1
      - nlpaug==1.1.11
      - nltk==3.9.1
      - numba==0.60.0
      - numpy==1.25.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.575.51
      - nvidia-ml-py3==7.352.0
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.3.1
      - ollama==0.5.1
      - omegaconf==2.3.0
      - openai==1.88.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openpyxl==3.1.5
      - openxlab==0.0.11
      - opt-einsum==3.4.0
      - optuna==4.4.0
      - ordered-set==4.1.0
      - orjson==3.11.1
      - pandas==2.3.0
      - patsy==1.0.1
      - pdf2image==1.17.0
      - peft==0.17.1
      - pillow==11.3.0
      - plotly==6.2.0
      - preshed==3.0.10
      - prettytable==3.16.0
      - prometheus-client==0.22.1
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==3.20.3
      - psutil==7.0.0
      - py-spy==0.4.1
      - py4j==0.10.9.9
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyautogen==0.9.0
      - pycryptodome==3.23.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pytesseract==0.3.13
      - python-dotenv==1.1.0
      - python-graphviz==0.21
      - pytorch-lightning==2.5.2
      - pytorch-metric-learning==2.8.1
      - pytz==2025.2
      - pyvirtualdisplay==3.0
      - pyyaml==6.0.2
      - ray==2.44.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - rich==14.1.0
      - rpds-py==0.26.0
      - rsa==4.9.1
      - s3transfer==0.13.1
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.32.0
      - seqeval==1.2.2
      - setproctitle==1.3.6
      - shellingham==1.5.4
      - skops==0.9.0
      - smart-open==7.3.0.post1
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.42
      - srsly==2.5.1
      - statsforecast==2.0.1
      - statsmodels==0.14.5
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.4
      - tensorflow==2.11.1
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - text-unidecode==1.3
      - thinc==8.3.4
      - tifffile==2024.8.30
      - tiktoken==0.9.0
      - timm==1.0.3
      - tokenizers==0.13.3
      - toolz==0.12.1
      - torch==2.6.0
      - torchaudio==2.0.1+cu118
      - torchmetrics==1.7.4
      - torchvision==0.21.0
      - toxinpred3==1.4
      - tqdm==4.67.1
      - transformers==4.28.1
      - triad==0.9.8
      - triton==3.3.1
      - typer==0.16.0
      - typing-inspection==0.4.1
      - uritemplate==4.2.0
      - urllib3==1.26.20
      - utilsforecast==0.2.11
      - virtualenv==20.33.0
      - wandb==0.21.0
      - wasabi==1.1.3
      - wcwidth==0.2.13
      - weasel==0.4.1
      - websockets==15.0.1
      - werkzeug==3.1.3
      - window-ops==0.0.15
      - wrapt==1.17.2
      - xgboost==2.1.4
      - xxhash==3.5.0
      - yarl==1.20.1
